-- Seed data: merchant, default policy, and the Rao & Sons catalog.

insert into merchant (id, name, legal_name, established, address, gstin, hours, phone, munim_note, razorpay_account, story)
values (1, 'Rao & Sons', 'Rao & Sons Provisions', 1978, '14 East Street, Camp, Pune 411001', '27AABCR4471F1Z3', '7:00 - 21:30, closed the last Tuesday of the month', '+91 20 2634 1188', 'Kulkarni (retired 2024). The book is now Munim.', 'acc_test_rao_and_sons', 'A dry-goods counter that still weighs goda masala by hand. WhatsApp for regulars. Invisible to every purchasing agent in the country.');

insert into policy (id, max_order_paise, auto_approve_below_paise, daily_cap_paise, allow_credit, max_payment_retries, hold_minutes, require_named_buyer, trip_next_payment)
values (1, 500000, 250000, 2000000, false, 1, 20, true, false);

insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('RCE-AMB-5', 'Ambemohar rice', 'rice', '5 kg sack', 5, 'kg', 78000, 82000, 14, 14, 5, 'Mulshi, near Pune', 'Short-grain, mango-blossom aroma. The local rice. Not a substitute for sona masoori in hotel breakfast.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('RCE-SON-5', 'Sona masoori rice', 'rice', '5 kg sack', 5, 'kg', 52000, 54500, 22, 22, 5, 'Raichur', 'Light, everyday rice. Fine for canteens. Not fragrant.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('RCE-KOL-1', 'Kolam rice', 'rice', '1 kg pack', 1, 'kg', 11800, 12500, 40, 40, 5, 'Vidarbha', 'Smaller pack for households. Use when a 5kg sack is too much.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('ATT-LOK-5', 'Lokwan atta', 'atta', '5 kg pack', 5, 'kg', 31000, 33500, 18, 18, 5, 'Madhya Pradesh, stone-ground in Pune', 'Mrs. Iyer''s usual. Medium-hard wheat. Do not swap for maida.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('ATT-BES-1', 'Besan', 'atta', '1 kg pack', 1, 'kg', 14500, 15200, 16, 16, 5, 'Akola', 'Not a wheat atta substitute. Only offer for bhajiya / kadhi.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('ATT-RAV-1', 'Rava (sooji)', 'atta', '1 kg pack', 1, 'kg', 7200, 7800, 24, 24, 5, 'Local mill', 'Medium grain. Right for upma, not for rava dosa (too coarse).', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('POH-THK-1', 'Thick poha', 'rice', '1 kg pack', 1, 'kg', 9500, 10200, 6, 6, 5, 'Maharashtra', 'The Pune breakfast poha. Hotels want THIS, not thin. Stock is tight this week - 6 kg on the shelf. Thin poha is a last-resort substitute and must be disclosed.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('POH-THN-1', 'Thin poha', 'rice', '1 kg pack', 1, 'kg', 8800, 9400, 19, 19, 5, 'Maharashtra', 'For chivda and evening snacks. Do not silently substitute for thick poha in a breakfast order.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('OIL-COC-1', 'Cold-pressed coconut oil', 'oil', '1 L bottle', 1, 'L', 42000, 46000, 9, 9, 5, 'Ratnagiri', 'Smells of the fruit. For cooking and hair. Pricey. Groundnut oil is the budget cooking substitute.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('OIL-GNT-1', 'Groundnut oil', 'oil', '1 L bottle', 1, 'L', 28000, 30500, 20, 20, 5, 'Saurashtra, packed in Pune', 'The house cooking oil. Fine for hotel kitchens.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('SPC-GOD-100', 'Goda masala', 'spice', '100 g tin', 100, 'g', 8500, 9000, 31, 31, 5, 'Ground in-house, Camp', 'The shop''s own mix. Coconut, sesame, stone flower. Not garam masala. Do not substitute.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('SPC-CHI-200', 'Guntur chilli powder', 'spice', '200 g pack', 200, 'g', 7800, 8400, 27, 27, 5, 'Guntur', 'Hot. Warn if the buyer asked for Kashmiri (colour, not heat).', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('SPC-TUR-200', 'Sangli turmeric', 'spice', '200 g pack', 200, 'g', 6200, 6800, 33, 33, 5, 'Sangli', 'Deep colour. The shop does not sell ''organic'' turmeric. This is the one.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('SPC-HNG-50', 'Hing (asafoetida)', 'spice', '50 g bottle', 50, 'g', 14500, 16000, 12, 12, 5, 'Compounded, food-grade', 'Compounded hing, not resin. Say so if asked. Strong - 50g lasts a household months.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('PCK-MNG-500', 'Mango pickle', 'pickle', '500 g jar', 500, 'g', 22000, 24000, 11, 11, 12, 'Made by the Rao kitchen, May batch', 'Oil pickle, mustard-heavy, not sweet. May batch. Mention the year if a buyer asks about last season.', true);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('PCK-LIM-400', 'Lime pickle', 'pickle', '400 g jar', 400, 'g', 18000, 19500, 8, 8, 12, 'Made by the Rao kitchen', 'Saltier, sharper. Good substitute if mango is out.', true);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('PAP-WAI-200', 'Wai ghat papad', 'papad', '200 g pack', 200, 'g', 6500, 7000, 25, 25, 5, 'Wai', 'Urad, not rice. Roast or fry. Hotels usually take 4-6 packs.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('TEA-CUT-250', 'Cutting chai blend', 'tea', '250 g pack', 250, 'g', 18000, 19500, 17, 17, 5, 'Assam CTC, blended in Camp', 'Strong CTC for milk tea. Four packs make 1 kg. Not a leaf tea. Do not sell this to someone asking for first-flush.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('TEA-ASM-250', 'Assam leaf tea', 'tea', '250 g pack', 250, 'g', 24000, 26000, 7, 7, 5, 'Dibrugarh', 'For cups, not cutting. Pricier. Only offer if they asked for leaf.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('DAL-TUR-1', 'Toor dal', 'pulse', '1 kg pack', 1, 'kg', 16800, 18000, 28, 28, 5, 'Gulbarga', 'Oily toor, the Maharashtrian default for varan.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('DAL-MNG-1', 'Moong dal', 'pulse', '1 kg pack', 1, 'kg', 15200, 16500, 21, 21, 5, 'Rajasthan', 'Split, skinned. For khichdi and sheera.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('SWT-JAG-1', 'Kolhapur jaggery', 'sweet', '1 kg block', 1, 'kg', 9800, 11000, 15, 15, 5, 'Kolhapur', 'Dark, wet, the proper gul. Not powder. Breaks with a knife.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('DRY-GHE-500', 'Buffalo ghee', 'dairy', '500 ml tin', 500, 'ml', 39000, 42000, 10, 10, 12, 'Phaltan dairy', 'Buffalo, not cow. Heavier aroma. Say so. Not cultured butter.', true);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('SWT-CHP-200', 'Banana chips', 'sweet', '200 g pack', 200, 'g', 8500, 9000, 13, 13, 12, 'Kerala, packed here', 'Salted, not sweet. A snack, not a grocery staple.', false);
insert into product (sku, name, category, unit, pack_qty, pack_unit, price_paise, mrp_paise, stock, seed_stock, gst_pct, origin, notes_for_agents, perishable) values ('SPC-CHT-150', 'Coconut chutney powder', 'spice', '150 g jar', 150, 'g', 12000, 13500, 9, 9, 5, 'Ground in-house', 'For idli/dosa when there is no fresh coconut. Not a wet chutney.', false);
insert into product_alias (product_sku, alias) values ('RCE-AMB-5', 'ambemohar');
insert into product_alias (product_sku, alias) values ('RCE-AMB-5', 'mango blossom rice');
insert into product_alias (product_sku, alias) values ('RCE-AMB-5', 'pune rice');
insert into product_alias (product_sku, alias) values ('RCE-AMB-5', 'wai rice');
insert into product_alias (product_sku, alias) values ('RCE-SON-5', 'sona masoori');
insert into product_alias (product_sku, alias) values ('RCE-SON-5', 'sona mahsuri');
insert into product_alias (product_sku, alias) values ('RCE-SON-5', 'everyday rice');
insert into product_alias (product_sku, alias) values ('RCE-KOL-1', 'kolam');
insert into product_alias (product_sku, alias) values ('RCE-KOL-1', 'jeera rice');
insert into product_alias (product_sku, alias) values ('ATT-LOK-5', 'atta');
insert into product_alias (product_sku, alias) values ('ATT-LOK-5', 'wheat flour');
insert into product_alias (product_sku, alias) values ('ATT-LOK-5', 'lokwan');
insert into product_alias (product_sku, alias) values ('ATT-LOK-5', 'chakki atta');
insert into product_alias (product_sku, alias) values ('ATT-LOK-5', '5kg atta');
insert into product_alias (product_sku, alias) values ('ATT-BES-1', 'besan');
insert into product_alias (product_sku, alias) values ('ATT-BES-1', 'gram flour');
insert into product_alias (product_sku, alias) values ('ATT-BES-1', 'chickpea flour');
insert into product_alias (product_sku, alias) values ('ATT-RAV-1', 'rava');
insert into product_alias (product_sku, alias) values ('ATT-RAV-1', 'sooji');
insert into product_alias (product_sku, alias) values ('ATT-RAV-1', 'semolina');
insert into product_alias (product_sku, alias) values ('ATT-RAV-1', 'upma rava');
insert into product_alias (product_sku, alias) values ('POH-THK-1', 'thick poha');
insert into product_alias (product_sku, alias) values ('POH-THK-1', 'jada poha');
insert into product_alias (product_sku, alias) values ('POH-THK-1', 'kande pohe poha');
insert into product_alias (product_sku, alias) values ('POH-THK-1', 'poha thick');
insert into product_alias (product_sku, alias) values ('POH-THK-1', 'beaten rice thick');
insert into product_alias (product_sku, alias) values ('POH-THN-1', 'thin poha');
insert into product_alias (product_sku, alias) values ('POH-THN-1', 'patla poha');
insert into product_alias (product_sku, alias) values ('POH-THN-1', 'nylon poha');
insert into product_alias (product_sku, alias) values ('OIL-COC-1', 'coconut oil');
insert into product_alias (product_sku, alias) values ('OIL-COC-1', 'nariyal tel');
insert into product_alias (product_sku, alias) values ('OIL-COC-1', 'cold pressed coconut');
insert into product_alias (product_sku, alias) values ('OIL-COC-1', 'virgin coconut oil');
insert into product_alias (product_sku, alias) values ('OIL-GNT-1', 'groundnut oil');
insert into product_alias (product_sku, alias) values ('OIL-GNT-1', 'peanut oil');
insert into product_alias (product_sku, alias) values ('OIL-GNT-1', 'mungfali tel');
insert into product_alias (product_sku, alias) values ('OIL-GNT-1', 'shengdana tel');
insert into product_alias (product_sku, alias) values ('SPC-GOD-100', 'goda masala');
insert into product_alias (product_sku, alias) values ('SPC-GOD-100', 'kala masala');
insert into product_alias (product_sku, alias) values ('SPC-GOD-100', 'pune masala');
insert into product_alias (product_sku, alias) values ('SPC-GOD-100', 'maharashtrian garam masala');
insert into product_alias (product_sku, alias) values ('SPC-CHI-200', 'chilli powder');
insert into product_alias (product_sku, alias) values ('SPC-CHI-200', 'lal mirch');
insert into product_alias (product_sku, alias) values ('SPC-CHI-200', 'guntur');
insert into product_alias (product_sku, alias) values ('SPC-CHI-200', 'tikhat');
insert into product_alias (product_sku, alias) values ('SPC-TUR-200', 'haldi');
insert into product_alias (product_sku, alias) values ('SPC-TUR-200', 'turmeric');
insert into product_alias (product_sku, alias) values ('SPC-TUR-200', 'halad');
insert into product_alias (product_sku, alias) values ('SPC-HNG-50', 'hing');
insert into product_alias (product_sku, alias) values ('SPC-HNG-50', 'asafoetida');
insert into product_alias (product_sku, alias) values ('SPC-HNG-50', 'perungayam');
insert into product_alias (product_sku, alias) values ('PCK-MNG-500', 'mango pickle');
insert into product_alias (product_sku, alias) values ('PCK-MNG-500', 'aam ka achar');
insert into product_alias (product_sku, alias) values ('PCK-MNG-500', 'lonche');
insert into product_alias (product_sku, alias) values ('PCK-MNG-500', 'pickle');
insert into product_alias (product_sku, alias) values ('PCK-LIM-400', 'lime pickle');
insert into product_alias (product_sku, alias) values ('PCK-LIM-400', 'nimbu achar');
insert into product_alias (product_sku, alias) values ('PCK-LIM-400', 'limbu lonche');
insert into product_alias (product_sku, alias) values ('PAP-WAI-200', 'papad');
insert into product_alias (product_sku, alias) values ('PAP-WAI-200', 'appalam');
insert into product_alias (product_sku, alias) values ('PAP-WAI-200', 'wai papad');
insert into product_alias (product_sku, alias) values ('PAP-WAI-200', 'udid papad');
insert into product_alias (product_sku, alias) values ('TEA-CUT-250', 'cutting chai');
insert into product_alias (product_sku, alias) values ('TEA-CUT-250', 'chai');
insert into product_alias (product_sku, alias) values ('TEA-CUT-250', 'tea');
insert into product_alias (product_sku, alias) values ('TEA-CUT-250', 'tapri chai');
insert into product_alias (product_sku, alias) values ('TEA-CUT-250', 'pune cutting');
insert into product_alias (product_sku, alias) values ('TEA-ASM-250', 'assam tea');
insert into product_alias (product_sku, alias) values ('TEA-ASM-250', 'leaf tea');
insert into product_alias (product_sku, alias) values ('TEA-ASM-250', 'orthodox tea');
insert into product_alias (product_sku, alias) values ('DAL-TUR-1', 'toor');
insert into product_alias (product_sku, alias) values ('DAL-TUR-1', 'arhar');
insert into product_alias (product_sku, alias) values ('DAL-TUR-1', 'tuvar');
insert into product_alias (product_sku, alias) values ('DAL-TUR-1', 'pigeon pea');
insert into product_alias (product_sku, alias) values ('DAL-MNG-1', 'moong');
insert into product_alias (product_sku, alias) values ('DAL-MNG-1', 'yellow moong');
insert into product_alias (product_sku, alias) values ('DAL-MNG-1', 'mung');
insert into product_alias (product_sku, alias) values ('SWT-JAG-1', 'jaggery');
insert into product_alias (product_sku, alias) values ('SWT-JAG-1', 'gul');
insert into product_alias (product_sku, alias) values ('SWT-JAG-1', 'gud');
insert into product_alias (product_sku, alias) values ('SWT-JAG-1', 'kolhapur gul');
insert into product_alias (product_sku, alias) values ('DRY-GHE-500', 'ghee');
insert into product_alias (product_sku, alias) values ('DRY-GHE-500', 'tup');
insert into product_alias (product_sku, alias) values ('DRY-GHE-500', 'buffalo ghee');
insert into product_alias (product_sku, alias) values ('DRY-GHE-500', 'desi ghee');
insert into product_alias (product_sku, alias) values ('SWT-CHP-200', 'banana chips');
insert into product_alias (product_sku, alias) values ('SWT-CHP-200', 'kere chips');
insert into product_alias (product_sku, alias) values ('SWT-CHP-200', 'plantain chips');
insert into product_alias (product_sku, alias) values ('SPC-CHT-150', 'chutney powder');
insert into product_alias (product_sku, alias) values ('SPC-CHT-150', 'kobbari karam');
insert into product_alias (product_sku, alias) values ('SPC-CHT-150', 'dry chutney');
insert into product_alias (product_sku, alias) values ('SPC-CHT-150', 'thengai podi');
insert into product_substitution (product_sku, substitution_sku) values ('RCE-AMB-5', 'RCE-KOL-1');
insert into product_substitution (product_sku, substitution_sku) values ('RCE-SON-5', 'RCE-KOL-1');
insert into product_substitution (product_sku, substitution_sku) values ('RCE-KOL-1', 'RCE-SON-5');
insert into product_substitution (product_sku, substitution_sku) values ('ATT-LOK-5', 'ATT-BES-1');
insert into product_substitution (product_sku, substitution_sku) values ('POH-THK-1', 'POH-THN-1');
insert into product_substitution (product_sku, substitution_sku) values ('POH-THN-1', 'POH-THK-1');
insert into product_substitution (product_sku, substitution_sku) values ('OIL-COC-1', 'OIL-GNT-1');
insert into product_substitution (product_sku, substitution_sku) values ('OIL-GNT-1', 'OIL-COC-1');
insert into product_substitution (product_sku, substitution_sku) values ('SPC-CHI-200', 'SPC-TUR-200');
insert into product_substitution (product_sku, substitution_sku) values ('PCK-MNG-500', 'PCK-LIM-400');
insert into product_substitution (product_sku, substitution_sku) values ('PCK-LIM-400', 'PCK-MNG-500');
insert into product_substitution (product_sku, substitution_sku) values ('TEA-CUT-250', 'TEA-ASM-250');
insert into product_substitution (product_sku, substitution_sku) values ('TEA-ASM-250', 'TEA-CUT-250');
insert into product_substitution (product_sku, substitution_sku) values ('DAL-TUR-1', 'DAL-MNG-1');
insert into product_substitution (product_sku, substitution_sku) values ('DAL-MNG-1', 'DAL-TUR-1');
insert into product_substitution (product_sku, substitution_sku) values ('SWT-CHP-200', 'PAP-WAI-200');
