/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AisleRouteImport } from './routes/aisle'
import { Route as CounterRouteImport } from './routes/counter'
import { Route as GaddiRouteImport } from './routes/gaddi'
import { Route as OffersRouteImport } from './routes/offers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AisleRoute = AisleRouteImport.update({
  id: '/aisle',
  path: '/aisle',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const GaddiRoute = GaddiRouteImport.update({
  id: '/gaddi',
  path: '/gaddi',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aisle': typeof AisleRoute
  '/counter': typeof CounterRoute
  '/gaddi': typeof GaddiRoute
  '/offers': typeof OffersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aisle': typeof AisleRoute
  '/counter': typeof CounterRoute
  '/gaddi': typeof GaddiRoute
  '/offers': typeof OffersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aisle': typeof AisleRoute
  '/counter': typeof CounterRoute
  '/gaddi': typeof GaddiRoute
  '/offers': typeof OffersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aisle' | '/counter' | '/gaddi' | '/offers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aisle' | '/counter' | '/gaddi' | '/offers'
  id: '__root__' | '/' | '/aisle' | '/counter' | '/gaddi' | '/offers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AisleRoute: typeof AisleRoute
  CounterRoute: typeof CounterRoute
  GaddiRoute: typeof GaddiRoute
  OffersRoute: typeof OffersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aisle': {
      id: '/aisle'
      path: '/aisle'
      fullPath: '/aisle'
      preLoaderRoute: typeof AisleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaddi': {
      id: '/gaddi'
      path: '/gaddi'
      fullPath: '/gaddi'
      preLoaderRoute: typeof GaddiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AisleRoute: AisleRoute,
  CounterRoute: CounterRoute,
  GaddiRoute: GaddiRoute,
  OffersRoute: OffersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
