export type Category =
  | "rice"
  | "atta"
  | "oil"
  | "spice"
  | "pickle"
  | "tea"
  | "papad"
  | "pulse"
  | "sweet"
  | "dairy";

export type Product = {
  sku: string;
  name: string;
  aliases: string[];
  category: Category;
  unit: string;
  packQty: number;
  packUnit: string;
  pricePaise: number;
  mrpPaise: number;
  stock: number;
  gstPct: number;
  origin: string;
  notesForAgents: string;
  substitutions: string[];
  perishable: boolean;
};

export const MERCHANT = {
  name: "Guptaji & Sons",
  legal: "Guptaji & Sons Provisions",
  est: 1978,
  address: "14 Fraser Road, Patna, Bihar 800001",
  gstin: "10AABCR4471F1Z3",
  hours: "7:00 – 21:30, closed the last Tuesday of the month",
  phone: "+91 612 2634 1188",
  munim: "Kulkarni (retired 2024). The book is now Munim.",
  razorpayAccount: "acc_test_guptaji_and_sons",
  story:
    "A dry-goods counter in Patna that still weighs masalas by hand. WhatsApp for regulars. Invisible to every purchasing agent in the country.",
};

export const PRODUCTS: Product[] = [
  {
    sku: "RCE-AMB-5",
    name: "Ambemohar rice",
    aliases: ["ambemohar", "mango blossom rice", "bihar rice", "patna rice"],
    category: "rice",
    unit: "5 kg sack",
    packQty: 5,
    packUnit: "kg",
    pricePaise: 78000,
    mrpPaise: 82000,
    stock: 14,
    gstPct: 5,
    origin: "Buxar, Bihar",
    notesForAgents:
      "Short-grain, mango-blossom aroma. The local Bihar rice. Not a substitute for sona masoori in hotel breakfast.",
    substitutions: ["RCE-KOL-1"],
    perishable: false,
  },
  {
    sku: "RCE-SON-5",
    name: "Sona masoori rice",
    aliases: ["sona masoori", "sona mahsuri", "everyday rice"],
    category: "rice",
    unit: "5 kg sack",
    packQty: 5,
    packUnit: "kg",
    pricePaise: 52000,
    mrpPaise: 54500,
    stock: 22,
    gstPct: 5,
    origin: "Raichur",
    notesForAgents: "Light, everyday rice. Fine for canteens. Not fragrant.",
    substitutions: ["RCE-KOL-1"],
    perishable: false,
  },
  {
    sku: "RCE-KOL-1",
    name: "Kolam rice",
    aliases: ["kolam", "jeera rice"],
    category: "rice",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 11800,
    mrpPaise: 12500,
    stock: 40,
    gstPct: 5,
    origin: "Vidarbha",
    notesForAgents: "Smaller pack for households. Use when a 5kg sack is too much.",
    substitutions: ["RCE-SON-5"],
    perishable: false,
  },
  {
    sku: "ATT-LOK-5",
    name: "Lokwan atta",
    aliases: ["atta", "wheat flour", "lokwan", "chakki atta", "5kg atta"],
    category: "atta",
    unit: "5 kg pack",
    packQty: 5,
    packUnit: "kg",
    pricePaise: 31000,
    mrpPaise: 33500,
    stock: 18,
    gstPct: 5,
    origin: "Buxar, stone-ground in Patna",
    notesForAgents:
      "Mrs. Iyer's usual. Medium-hard wheat. Do not swap for maida.",
    substitutions: ["ATT-BES-1"],
    perishable: false,
  },
  {
    sku: "ATT-BES-1",
    name: "Besan",
    aliases: ["besan", "gram flour", "chickpea flour"],
    category: "atta",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 14500,
    mrpPaise: 15200,
    stock: 16,
    gstPct: 5,
    origin: "Akola",
    notesForAgents: "Not a wheat atta substitute. Only offer for bhajiya / kadhi.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "ATT-RAV-1",
    name: "Rava (sooji)",
    aliases: ["rava", "sooji", "semolina", "upma rava"],
    category: "atta",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 7200,
    mrpPaise: 7800,
    stock: 24,
    gstPct: 5,
    origin: "Local mill",
    notesForAgents: "Medium grain. Right for upma, not for rava dosa (too coarse).",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "POH-THK-1",
    name: "Thick poha",
    aliases: ["thick poha", "jada poha", "kande pohe poha", "poha thick", "beaten rice thick"],
    category: "rice",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 9500,
    mrpPaise: 10200,
    stock: 6,
    gstPct: 5,
    origin: "Maharashtra",
    notesForAgents:
      "The Bihar breakfast poha. Hotels want THIS, not thin. Stock is tight this week — 6 kg on the shelf. Thin poha is a last-resort substitute and must be disclosed.",
    substitutions: ["POH-THN-1"],
    perishable: false,
  },
  {
    sku: "POH-THN-1",
    name: "Thin poha",
    aliases: ["thin poha", "patla poha", "nylon poha"],
    category: "rice",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 8800,
    mrpPaise: 9400,
    stock: 19,
    gstPct: 5,
    origin: "Maharashtra",
    notesForAgents:
      "For chivda and evening snacks. Do not silently substitute for thick poha in a breakfast order.",
    substitutions: ["POH-THK-1"],
    perishable: false,
  },
  {
    sku: "OIL-COC-1",
    name: "Cold-pressed coconut oil",
    aliases: ["coconut oil", "nariyal tel", "cold pressed coconut", "virgin coconut oil"],
    category: "oil",
    unit: "1 L bottle",
    packQty: 1,
    packUnit: "L",
    pricePaise: 42000,
    mrpPaise: 46000,
    stock: 9,
    gstPct: 5,
    origin: "Ratnagiri",
    notesForAgents:
      "Smells of the fruit. For cooking and hair. Pricey. Groundnut oil is the budget cooking substitute.",
    substitutions: ["OIL-GNT-1"],
    perishable: false,
  },
  {
    sku: "OIL-GNT-1",
    name: "Groundnut oil",
    aliases: ["groundnut oil", "peanut oil", "mungfali tel", "shengdana tel"],
    category: "oil",
    unit: "1 L bottle",
    packQty: 1,
    packUnit: "L",
    pricePaise: 28000,
    mrpPaise: 30500,
    stock: 20,
    gstPct: 5,
    origin: "Saurashtra, packed in Patna",
    notesForAgents: "The house cooking oil. Fine for hotel kitchens.",
    substitutions: ["OIL-COC-1"],
    perishable: false,
  },
  {
    sku: "SPC-GOD-100",
    name: "Goda masala",
    aliases: ["bihari masala", "kala masala", "patna masala", "garam masala"],
    category: "spice",
    unit: "100 g tin",
    packQty: 100,
    packUnit: "g",
    pricePaise: 8500,
    mrpPaise: 9000,
    stock: 31,
    gstPct: 5,
    origin: "Ground in-house, Patna",
    notesForAgents:
      "The shop's own mix. Coconut, sesame, stone flower. Not garam masala. Do not substitute.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "SPC-CHI-200",
    name: "Guntur chilli powder",
    aliases: ["chilli powder", "lal mirch", "guntur", "tikhat"],
    category: "spice",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 7800,
    mrpPaise: 8400,
    stock: 27,
    gstPct: 5,
    origin: "Guntur",
    notesForAgents: "Hot. Warn if the buyer asked for Kashmiri (colour, not heat).",
    substitutions: ["SPC-TUR-200"],
    perishable: false,
  },
  {
    sku: "SPC-TUR-200",
    name: "Sangli turmeric",
    aliases: ["haldi", "turmeric", "halad"],
    category: "spice",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 6200,
    mrpPaise: 6800,
    stock: 33,
    gstPct: 5,
    origin: "Sangli",
    notesForAgents: "Deep colour. The shop does not sell 'organic' turmeric. This is the one.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "SPC-HNG-50",
    name: "Hing (asafoetida)",
    aliases: ["hing", "asafoetida", "perungayam"],
    category: "spice",
    unit: "50 g bottle",
    packQty: 50,
    packUnit: "g",
    pricePaise: 14500,
    mrpPaise: 16000,
    stock: 12,
    gstPct: 5,
    origin: "Compounded, food-grade",
    notesForAgents: "Compounded hing, not resin. Say so if asked. Strong — 50g lasts a household months.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "PCK-MNG-500",
    name: "Mango pickle",
    aliases: ["mango pickle", "aam ka achar", "lonche", "pickle"],
    category: "pickle",
    unit: "500 g jar",
    packQty: 500,
    packUnit: "g",
    pricePaise: 22000,
    mrpPaise: 24000,
    stock: 11,
    gstPct: 12,
    origin: "Made by the Guptaji kitchen, May batch",
    notesForAgents:
      "Oil pickle, mustard-heavy, not sweet. May batch. Mention the year if a buyer asks about last season.",
    substitutions: ["PCK-LIM-400"],
    perishable: true,
  },
  {
    sku: "PCK-LIM-400",
    name: "Lime pickle",
    aliases: ["lime pickle", "nimbu achar", "limbu lonche"],
    category: "pickle",
    unit: "400 g jar",
    packQty: 400,
    packUnit: "g",
    pricePaise: 18000,
    mrpPaise: 19500,
    stock: 8,
    gstPct: 12,
    origin: "Made by the Guptaji kitchen",
    notesForAgents: "Saltier, sharper. Good substitute if mango is out.",
    substitutions: ["PCK-MNG-500"],
    perishable: true,
  },
  {
    sku: "PAP-WAI-200",
    name: "Wai ghat papad",
    aliases: ["papad", "appalam", "wai papad", "udid papad"],
    category: "papad",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 6500,
    mrpPaise: 7000,
    stock: 25,
    gstPct: 5,
    origin: "Wai",
    notesForAgents: "Urad, not rice. Roast or fry. Hotels usually take 4–6 packs.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "TEA-CUT-250",
    name: "Cutting chai blend",
    aliases: ["cutting chai", "chai", "tea", "tapri chai", "patna cutting"],
    category: "tea",
    unit: "250 g pack",
    packQty: 250,
    packUnit: "g",
    pricePaise: 18000,
    mrpPaise: 19500,
    stock: 17,
    gstPct: 5,
    origin: "Assam CTC, blended in Patna",
    notesForAgents:
      "Strong CTC for milk tea. Four packs make 1 kg. Not a leaf tea. Do not sell this to someone asking for first-flush.",
    substitutions: ["TEA-ASM-250"],
    perishable: false,
  },
  {
    sku: "TEA-ASM-250",
    name: "Assam leaf tea",
    aliases: ["assam tea", "leaf tea", "orthodox tea"],
    category: "tea",
    unit: "250 g pack",
    packQty: 250,
    packUnit: "g",
    pricePaise: 24000,
    mrpPaise: 26000,
    stock: 7,
    gstPct: 5,
    origin: "Dibrugarh",
    notesForAgents: "For cups, not cutting. Pricier. Only offer if they asked for leaf.",
    substitutions: ["TEA-CUT-250"],
    perishable: false,
  },
  {
    sku: "DAL-TUR-1",
    name: "Toor dal",
    aliases: ["toor", "arhar", "tuvar", "pigeon pea"],
    category: "pulse",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 16800,
    mrpPaise: 18000,
    stock: 28,
    gstPct: 5,
    origin: "Gulbarga",
    notesForAgents: "Oily toor, the Maharashtrian default for varan.",
    substitutions: ["DAL-MNG-1"],
    perishable: false,
  },
  {
    sku: "DAL-MNG-1",
    name: "Moong dal",
    aliases: ["moong", "yellow moong", "mung"],
    category: "pulse",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 15200,
    mrpPaise: 16500,
    stock: 21,
    gstPct: 5,
    origin: "Rajasthan",
    notesForAgents: "Split, skinned. For khichdi and sheera.",
    substitutions: ["DAL-TUR-1"],
    perishable: false,
  },
  {
    sku: "SWT-JAG-1",
    name: "Kolhapur jaggery",
    aliases: ["jaggery", "gul", "gud", "kolhapur gul"],
    category: "sweet",
    unit: "1 kg block",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 9800,
    mrpPaise: 11000,
    stock: 15,
    gstPct: 5,
    origin: "Kolhapur",
    notesForAgents: "Dark, wet, the proper gul. Not powder. Breaks with a knife.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "DRY-GHE-500",
    name: "Buffalo ghee",
    aliases: ["ghee", "tup", "buffalo ghee", "desi ghee"],
    category: "dairy",
    unit: "500 ml tin",
    packQty: 500,
    packUnit: "ml",
    pricePaise: 39000,
    mrpPaise: 42000,
    stock: 10,
    gstPct: 12,
    origin: "Phaltan dairy",
    notesForAgents: "Buffalo, not cow. Heavier aroma. Say so. Not cultured butter.",
    substitutions: [],
    perishable: true,
  },
  {
    sku: "SWT-CHP-200",
    name: "Banana chips",
    aliases: ["banana chips", "kere chips", "plantain chips"],
    category: "sweet",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 8500,
    mrpPaise: 9000,
    stock: 13,
    gstPct: 12,
    origin: "Kerala, packed here",
    notesForAgents: "Salted, not sweet. A snack, not a grocery staple.",
    substitutions: ["PAP-WAI-200"],
    perishable: false,
  },
  {
    sku: "SPC-CHT-150",
    name: "Coconut chutney powder",
    aliases: ["chutney powder", "kobbari karam", "dry chutney", "thengai podi"],
    category: "spice",
    unit: "150 g jar",
    packQty: 150,
    packUnit: "g",
    pricePaise: 12000,
    mrpPaise: 13500,
    stock: 9,
    gstPct: 5,
    origin: "Ground in-house",
    notesForAgents: "For idli/dosa when there is no fresh coconut. Not a wet chutney.",
    substitutions: [],
    perishable: false,
  },
];

export const CATEGORY_LABEL: Record<Category, string> = {
  rice: "Rice & poha",
  atta: "Flours",
  oil: "Oils",
  spice: "Masala",
  pickle: "Pickle",
  tea: "Tea",
  papad: "Papad",
  pulse: "Dal",
  sweet: "Gul & snack",
  dairy: "Dairy",
};

export function getProduct(sku: string) {
  return PRODUCTS.find((p) => p.sku === sku);
}

export function searchProducts(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return PRODUCTS;
  return PRODUCTS.filter((p) => {
    const hay = [p.name, p.sku, p.origin, p.notesForAgents, ...p.aliases, p.category]
      .join(" ")
      .toLowerCase();
    return hay.includes(q);
  });
}

export function catalogForAgents() {
  return PRODUCTS.map((p) => ({
    sku: p.sku,
    name: p.name,
    aliases: p.aliases,
    category: p.category,
    unit: p.unit,
    pack_qty: p.packQty,
    pack_unit: p.packUnit,
    price_inr: p.pricePaise / 100,
    mrp_inr: p.mrpPaise / 100,
    currency: "INR",
    stock: p.stock,
    gst_pct: p.gstPct,
    origin: p.origin,
    notes: p.notesForAgents,
    substitutions: p.substitutions,
    perishable: p.perishable,
  }));
}
