export type Category =
  | "rice"
  | "atta"
  | "oil"
  | "spice"
  | "pickle"
  | "tea"
  | "papad"
  | "pulse"
  | "sweet"
  | "dairy"
  | "sugar"
  | "dry-fruit"
  | "masala-mix"
  | "snack"
  | "soap";

export type Product = {
  sku: string;
  name: string;
  aliases: string[];
  category: Category;
  unit: string;
  packQty: number;
  packUnit: string;
  pricePaise: number;
  mrpPaise: number;
  stock: number;
  gstPct: number;
  origin: string;
  notesForAgents: string;
  substitutions: string[];
  perishable: boolean;
};

export const MERCHANT = {
  name: "Guptaji & Sons",
  legal: "Guptaji & Sons Provisions",
  est: 1978,
  address: "14 Fraser Road, Patna, Bihar 800001",
  gstin: "10AABCR4471F1Z3",
  hours: "7:00 – 21:30, closed the last Tuesday of the month",
  phone: "+91 612 2634 1188",
  munim: "Kulkarni (retired 2024). The book is now Munim.",
  razorpayAccount: "acc_test_guptaji_and_sons",
  story:
    "A dry-goods counter in Patna that still weighs masalas by hand. WhatsApp for regulars. Invisible to every purchasing agent in the country.",
};

export const PRODUCTS: Product[] = [
  // ─── RICE & POHA ────────────────────────────────────────────────────────────
  {
    sku: "RCE-AMB-5",
    name: "Ambemohar rice",
    aliases: ["ambemohar", "mango blossom rice", "bihar rice", "patna rice"],
    category: "rice",
    unit: "5 kg sack",
    packQty: 5,
    packUnit: "kg",
    pricePaise: 78000,
    mrpPaise: 82000,
    stock: 14,
    gstPct: 5,
    origin: "Buxar, Bihar",
    notesForAgents:
      "Short-grain, mango-blossom aroma. The local Bihar rice. Not a substitute for sona masoori in hotel breakfast.",
    substitutions: ["RCE-KOL-1"],
    perishable: false,
  },
  {
    sku: "RCE-SON-5",
    name: "Sona masoori rice",
    aliases: ["sona masoori", "sona mahsuri", "everyday rice"],
    category: "rice",
    unit: "5 kg sack",
    packQty: 5,
    packUnit: "kg",
    pricePaise: 52000,
    mrpPaise: 54500,
    stock: 22,
    gstPct: 5,
    origin: "Raichur",
    notesForAgents: "Light, everyday rice. Fine for canteens. Not fragrant.",
    substitutions: ["RCE-KOL-1"],
    perishable: false,
  },
  {
    sku: "RCE-KOL-1",
    name: "Kolam rice",
    aliases: ["kolam", "jeera rice"],
    category: "rice",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 11800,
    mrpPaise: 12500,
    stock: 40,
    gstPct: 5,
    origin: "Vidarbha",
    notesForAgents: "Smaller pack for households. Use when a 5kg sack is too much.",
    substitutions: ["RCE-SON-5"],
    perishable: false,
  },
  {
    sku: "RCE-BAM-5",
    name: "Basmati rice (long grain)",
    aliases: ["basmati", "long grain rice", "biryani rice", "dum rice"],
    category: "rice",
    unit: "5 kg sack",
    packQty: 5,
    packUnit: "kg",
    pricePaise: 115000,
    mrpPaise: 125000,
    stock: 8,
    gstPct: 5,
    origin: "Dehradun",
    notesForAgents:
      "Aged, fragrant. Used for biryani and dum. Not suitable for everyday dal-chawal. Priciest rice in the shop.",
    substitutions: ["RCE-AMB-5"],
    perishable: false,
  },
  {
    sku: "RCE-IND-25",
    name: "Indrayani rice",
    aliases: ["indrayani", "sugartha", "khushboo rice"],
    category: "rice",
    unit: "25 kg sack",
    packQty: 25,
    packUnit: "kg",
    pricePaise: 285000,
    mrpPaise: 300000,
    stock: 4,
    gstPct: 5,
    origin: "Pune district",
    notesForAgents:
      "Bulk sack for canteens and hostels. Fragrant medium-grain. Minimum order 1 sack. Carry charge applies above 2 sacks.",
    substitutions: ["RCE-SON-5"],
    perishable: false,
  },
  {
    sku: "POH-THK-1",
    name: "Thick poha",
    aliases: ["thick poha", "jada poha", "kande pohe poha", "poha thick", "beaten rice thick"],
    category: "rice",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 9500,
    mrpPaise: 10200,
    stock: 6,
    gstPct: 5,
    origin: "Maharashtra",
    notesForAgents:
      "The Bihar breakfast poha. Hotels want THIS, not thin. Stock is tight this week — 6 kg on the shelf. Thin poha is a last-resort substitute and must be disclosed.",
    substitutions: ["POH-THN-1"],
    perishable: false,
  },
  {
    sku: "POH-THN-1",
    name: "Thin poha",
    aliases: ["thin poha", "patla poha", "nylon poha"],
    category: "rice",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 8800,
    mrpPaise: 9400,
    stock: 19,
    gstPct: 5,
    origin: "Maharashtra",
    notesForAgents:
      "For chivda and evening snacks. Do not silently substitute for thick poha in a breakfast order.",
    substitutions: ["POH-THK-1"],
    perishable: false,
  },

  // ─── ATTA & FLOUR ───────────────────────────────────────────────────────────
  {
    sku: "ATT-LOK-5",
    name: "Lokwan atta",
    aliases: ["atta", "wheat flour", "lokwan", "chakki atta", "5kg atta"],
    category: "atta",
    unit: "5 kg pack",
    packQty: 5,
    packUnit: "kg",
    pricePaise: 31000,
    mrpPaise: 33500,
    stock: 18,
    gstPct: 5,
    origin: "Buxar, stone-ground in Patna",
    notesForAgents:
      "Mrs. Iyer's usual. Medium-hard wheat. Do not swap for maida.",
    substitutions: ["ATT-BES-1"],
    perishable: false,
  },
  {
    sku: "ATT-BES-1",
    name: "Besan",
    aliases: ["besan", "gram flour", "chickpea flour"],
    category: "atta",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 14500,
    mrpPaise: 15200,
    stock: 16,
    gstPct: 5,
    origin: "Akola",
    notesForAgents: "Not a wheat atta substitute. Only offer for bhajiya / kadhi.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "ATT-RAV-1",
    name: "Rava (sooji)",
    aliases: ["rava", "sooji", "semolina", "upma rava"],
    category: "atta",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 7200,
    mrpPaise: 7800,
    stock: 24,
    gstPct: 5,
    origin: "Local mill",
    notesForAgents: "Medium grain. Right for upma, not for rava dosa (too coarse).",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "ATT-MAI-1",
    name: "Maida (refined flour)",
    aliases: ["maida", "all purpose flour", "refined flour", "white flour"],
    category: "atta",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 5800,
    mrpPaise: 6200,
    stock: 20,
    gstPct: 5,
    origin: "Local mill, Patna",
    notesForAgents:
      "For paratha, naan, or bakery use. Never substitute for atta. Clarify if buyer asks for 'flour'.",
    substitutions: ["ATT-LOK-5"],
    perishable: false,
  },
  {
    sku: "ATT-RAG-500",
    name: "Ragi flour (nachni)",
    aliases: ["ragi", "nachni", "finger millet flour", "mandua atta"],
    category: "atta",
    unit: "500 g pack",
    packQty: 500,
    packUnit: "g",
    pricePaise: 9500,
    mrpPaise: 10500,
    stock: 10,
    gstPct: 5,
    origin: "Karnataka",
    notesForAgents:
      "Health-conscious buyers. Good for ragi roti and porridge. Not available in 1 kg — two packs make a kilo.",
    substitutions: [],
    perishable: false,
  },

  // ─── OILS ───────────────────────────────────────────────────────────────────
  {
    sku: "OIL-COC-1",
    name: "Cold-pressed coconut oil",
    aliases: ["coconut oil", "nariyal tel", "cold pressed coconut", "virgin coconut oil"],
    category: "oil",
    unit: "1 L bottle",
    packQty: 1,
    packUnit: "L",
    pricePaise: 42000,
    mrpPaise: 46000,
    stock: 9,
    gstPct: 5,
    origin: "Ratnagiri",
    notesForAgents:
      "Smells of the fruit. For cooking and hair. Pricey. Groundnut oil is the budget cooking substitute.",
    substitutions: ["OIL-GNT-1"],
    perishable: false,
  },
  {
    sku: "OIL-GNT-1",
    name: "Groundnut oil",
    aliases: ["groundnut oil", "peanut oil", "mungfali tel", "shengdana tel"],
    category: "oil",
    unit: "1 L bottle",
    packQty: 1,
    packUnit: "L",
    pricePaise: 28000,
    mrpPaise: 30500,
    stock: 20,
    gstPct: 5,
    origin: "Saurashtra, packed in Patna",
    notesForAgents: "The house cooking oil. Fine for hotel kitchens.",
    substitutions: ["OIL-COC-1"],
    perishable: false,
  },
  {
    sku: "OIL-MUS-1",
    name: "Mustard oil",
    aliases: ["mustard oil", "sarson tel", "kachchi ghani", "bihar mustard oil"],
    category: "oil",
    unit: "1 L bottle",
    packQty: 1,
    packUnit: "L",
    pricePaise: 24000,
    mrpPaise: 26000,
    stock: 30,
    gstPct: 5,
    origin: "Muzaffarpur, Bihar",
    notesForAgents:
      "The Bihar cooking oil — used for sabzi, achaar, and fish. Strong pungent taste. Kachchi ghani (cold pressed). Most Bihar households use this as daily oil.",
    substitutions: ["OIL-GNT-1"],
    perishable: false,
  },
  {
    sku: "OIL-SES-500",
    name: "Til oil (sesame)",
    aliases: ["til oil", "sesame oil", "gingelly oil", "til tel"],
    category: "oil",
    unit: "500 ml bottle",
    packQty: 500,
    packUnit: "ml",
    pricePaise: 31000,
    mrpPaise: 34000,
    stock: 7,
    gstPct: 5,
    origin: "Rajasthan",
    notesForAgents:
      "Cold-pressed, unrefined. For festive cooking and winter laddoos. Low stock. Not for daily use.",
    substitutions: ["OIL-GNT-1"],
    perishable: false,
  },
  {
    sku: "OIL-GNT-5",
    name: "Groundnut oil (5L)",
    aliases: ["5 litre groundnut", "5l oil", "bulk groundnut oil", "canteen oil"],
    category: "oil",
    unit: "5 L tin",
    packQty: 5,
    packUnit: "L",
    pricePaise: 132000,
    mrpPaise: 145000,
    stock: 6,
    gstPct: 5,
    origin: "Saurashtra, packed in Patna",
    notesForAgents:
      "Bulk tin for canteens and hotels. Better per-litre price than 1L bottles. Max 3 tins per order unless pre-arranged.",
    substitutions: ["OIL-GNT-1"],
    perishable: false,
  },

  // ─── SPICES ─────────────────────────────────────────────────────────────────
  {
    sku: "SPC-GOD-100",
    name: "Goda masala",
    aliases: ["bihari masala", "kala masala", "patna masala", "garam masala"],
    category: "spice",
    unit: "100 g tin",
    packQty: 100,
    packUnit: "g",
    pricePaise: 8500,
    mrpPaise: 9000,
    stock: 31,
    gstPct: 5,
    origin: "Ground in-house, Patna",
    notesForAgents:
      "The shop's own mix. Coconut, sesame, stone flower. Not garam masala. Do not substitute.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "SPC-CHI-200",
    name: "Guntur chilli powder",
    aliases: ["chilli powder", "lal mirch", "guntur", "tikhat"],
    category: "spice",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 7800,
    mrpPaise: 8400,
    stock: 27,
    gstPct: 5,
    origin: "Guntur",
    notesForAgents: "Hot. Warn if the buyer asked for Kashmiri (colour, not heat).",
    substitutions: ["SPC-TUR-200"],
    perishable: false,
  },
  {
    sku: "SPC-KAS-100",
    name: "Kashmiri chilli powder",
    aliases: ["kashmiri mirch", "deggi mirch", "kashmiri red chilli", "colour chilli"],
    category: "spice",
    unit: "100 g pack",
    packQty: 100,
    packUnit: "g",
    pricePaise: 9200,
    mrpPaise: 10000,
    stock: 15,
    gstPct: 5,
    origin: "Kashmir",
    notesForAgents:
      "Mild heat, deep red colour. Used for tandoori and butter chicken colour. Different from Guntur — do not substitute silently.",
    substitutions: ["SPC-CHI-200"],
    perishable: false,
  },
  {
    sku: "SPC-TUR-200",
    name: "Sangli turmeric",
    aliases: ["haldi", "turmeric", "halad"],
    category: "spice",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 6200,
    mrpPaise: 6800,
    stock: 33,
    gstPct: 5,
    origin: "Sangli",
    notesForAgents: "Deep colour. The shop does not sell 'organic' turmeric. This is the one.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "SPC-HNG-50",
    name: "Hing (asafoetida)",
    aliases: ["hing", "asafoetida", "perungayam"],
    category: "spice",
    unit: "50 g bottle",
    packQty: 50,
    packUnit: "g",
    pricePaise: 14500,
    mrpPaise: 16000,
    stock: 12,
    gstPct: 5,
    origin: "Compounded, food-grade",
    notesForAgents: "Compounded hing, not resin. Say so if asked. Strong — 50g lasts a household months.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "SPC-JER-100",
    name: "Jeera (cumin seeds)",
    aliases: ["jeera", "cumin", "zeera", "jeere"],
    category: "spice",
    unit: "100 g pack",
    packQty: 100,
    packUnit: "g",
    pricePaise: 5800,
    mrpPaise: 6500,
    stock: 35,
    gstPct: 5,
    origin: "Rajasthan",
    notesForAgents: "Whole seeds. For tadka and rice. Very common item. Always in stock.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "SPC-MUS-100",
    name: "Rai (mustard seeds)",
    aliases: ["rai", "mustard seeds", "sarson", "mohri"],
    category: "spice",
    unit: "100 g pack",
    packQty: 100,
    packUnit: "g",
    pricePaise: 3800,
    mrpPaise: 4200,
    stock: 40,
    gstPct: 5,
    origin: "Saurashtra",
    notesForAgents: "Black mustard seeds for tadka and pickle. Bihar kitchen staple.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "SPC-COR-200",
    name: "Dhania powder (coriander)",
    aliases: ["dhania", "coriander powder", "dhania powder"],
    category: "spice",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 5200,
    mrpPaise: 5800,
    stock: 28,
    gstPct: 5,
    origin: "Rajasthan",
    notesForAgents: "Ground coriander. Paired with jeera for sabzi base. High turnover item.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "SPC-GAR-200",
    name: "Garam masala (house blend)",
    aliases: ["garam masala", "whole spice mix", "spice mix"],
    category: "masala-mix",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 13000,
    mrpPaise: 14500,
    stock: 18,
    gstPct: 5,
    origin: "Blended in-house, Patna",
    notesForAgents:
      "The shop blend. Cardamom, clove, cinnamon, black pepper, bay leaf. Not goda masala. Strong — a little goes far.",
    substitutions: ["SPC-GOD-100"],
    perishable: false,
  },
  {
    sku: "SPC-CHT-150",
    name: "Coconut chutney powder",
    aliases: ["chutney powder", "kobbari karam", "dry chutney", "thengai podi"],
    category: "spice",
    unit: "150 g jar",
    packQty: 150,
    packUnit: "g",
    pricePaise: 12000,
    mrpPaise: 13500,
    stock: 9,
    gstPct: 5,
    origin: "Ground in-house",
    notesForAgents: "For idli/dosa when there is no fresh coconut. Not a wet chutney.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "SPC-AMS-100",
    name: "Amchur powder (dry mango)",
    aliases: ["amchur", "dry mango powder", "khatai"],
    category: "spice",
    unit: "100 g pack",
    packQty: 100,
    packUnit: "g",
    pricePaise: 6800,
    mrpPaise: 7500,
    stock: 20,
    gstPct: 5,
    origin: "UP",
    notesForAgents: "Souring agent for chhole and sabzi. Not the same as aamchur candy. Tart, not sweet.",
    substitutions: [],
    perishable: false,
  },

  // ─── PICKLES ────────────────────────────────────────────────────────────────
  {
    sku: "PCK-MNG-500",
    name: "Mango pickle",
    aliases: ["mango pickle", "aam ka achar", "lonche", "pickle"],
    category: "pickle",
    unit: "500 g jar",
    packQty: 500,
    packUnit: "g",
    pricePaise: 22000,
    mrpPaise: 24000,
    stock: 11,
    gstPct: 12,
    origin: "Made by the Guptaji kitchen, May batch",
    notesForAgents:
      "Oil pickle, mustard-heavy, not sweet. May batch. Mention the year if a buyer asks about last season.",
    substitutions: ["PCK-LIM-400"],
    perishable: true,
  },
  {
    sku: "PCK-LIM-400",
    name: "Lime pickle",
    aliases: ["lime pickle", "nimbu achar", "limbu lonche"],
    category: "pickle",
    unit: "400 g jar",
    packQty: 400,
    packUnit: "g",
    pricePaise: 18000,
    mrpPaise: 19500,
    stock: 8,
    gstPct: 12,
    origin: "Made by the Guptaji kitchen",
    notesForAgents: "Saltier, sharper. Good substitute if mango is out.",
    substitutions: ["PCK-MNG-500"],
    perishable: true,
  },
  {
    sku: "PCK-GAR-300",
    name: "Garlic pickle",
    aliases: ["garlic pickle", "lehsun achar", "lahsun ka achar"],
    category: "pickle",
    unit: "300 g jar",
    packQty: 300,
    packUnit: "g",
    pricePaise: 19500,
    mrpPaise: 21000,
    stock: 5,
    gstPct: 12,
    origin: "Made by the Guptaji kitchen",
    notesForAgents:
      "Strong. Low stock. Popular among truck drivers and dhabas. Not available in bulk.",
    substitutions: ["PCK-MNG-500"],
    perishable: true,
  },
  {
    sku: "PCK-GNG-250",
    name: "Ginger pickle (adrak achar)",
    aliases: ["ginger pickle", "adrak achar", "ginger achaar"],
    category: "pickle",
    unit: "250 g jar",
    packQty: 250,
    packUnit: "g",
    pricePaise: 16000,
    mrpPaise: 17500,
    stock: 6,
    gstPct: 12,
    origin: "Made by the Guptaji kitchen",
    notesForAgents:
      "Rare item — not many shops make this. Ginger + mustard oil + salt. Bihar winter specialty.",
    substitutions: ["PCK-LIM-400"],
    perishable: true,
  },

  // ─── PULSES / DAL ───────────────────────────────────────────────────────────
  {
    sku: "DAL-TUR-1",
    name: "Toor dal",
    aliases: ["toor", "arhar", "tuvar", "pigeon pea"],
    category: "pulse",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 16800,
    mrpPaise: 18000,
    stock: 28,
    gstPct: 5,
    origin: "Gulbarga",
    notesForAgents: "Oily toor, the Maharashtrian default for varan.",
    substitutions: ["DAL-MNG-1"],
    perishable: false,
  },
  {
    sku: "DAL-MNG-1",
    name: "Moong dal",
    aliases: ["moong", "yellow moong", "mung"],
    category: "pulse",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 15200,
    mrpPaise: 16500,
    stock: 21,
    gstPct: 5,
    origin: "Rajasthan",
    notesForAgents: "Split, skinned. For khichdi and sheera.",
    substitutions: ["DAL-TUR-1"],
    perishable: false,
  },
  {
    sku: "DAL-CHA-1",
    name: "Chana dal",
    aliases: ["chana dal", "split chickpea", "cholar dal", "bengal gram"],
    category: "pulse",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 12800,
    mrpPaise: 13800,
    stock: 25,
    gstPct: 5,
    origin: "Rajasthan",
    notesForAgents: "Split Bengal gram. For dal tadka and halwa. Not besan.",
    substitutions: ["DAL-MNG-1"],
    perishable: false,
  },
  {
    sku: "DAL-URA-1",
    name: "Urad dal (black)",
    aliases: ["urad", "black gram", "black urad", "whole urad"],
    category: "pulse",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 17500,
    mrpPaise: 19000,
    stock: 15,
    gstPct: 5,
    origin: "Andhra Pradesh",
    notesForAgents:
      "Whole black urad. For dal makhani and idli batter. Do not confuse with white split urad.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "DAL-MAS-1",
    name: "Masoor dal (red lentils)",
    aliases: ["masoor", "red lentil", "malka dal", "pink lentil"],
    category: "pulse",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 14000,
    mrpPaise: 15500,
    stock: 22,
    gstPct: 5,
    origin: "Madhya Pradesh",
    notesForAgents: "Split red lentils. Fastest cooking dal. Bihar daily dal for many households.",
    substitutions: ["DAL-MNG-1"],
    perishable: false,
  },

  // ─── TEA ───────────────────────────────────────────────────────────────────
  {
    sku: "TEA-CUT-250",
    name: "Cutting chai blend",
    aliases: ["cutting chai", "chai", "tea", "tapri chai", "patna cutting"],
    category: "tea",
    unit: "250 g pack",
    packQty: 250,
    packUnit: "g",
    pricePaise: 18000,
    mrpPaise: 19500,
    stock: 17,
    gstPct: 5,
    origin: "Assam CTC, blended in Patna",
    notesForAgents:
      "Strong CTC for milk tea. Four packs make 1 kg. Not a leaf tea. Do not sell this to someone asking for first-flush.",
    substitutions: ["TEA-ASM-250"],
    perishable: false,
  },
  {
    sku: "TEA-ASM-250",
    name: "Assam leaf tea",
    aliases: ["assam tea", "leaf tea", "orthodox tea"],
    category: "tea",
    unit: "250 g pack",
    packQty: 250,
    packUnit: "g",
    pricePaise: 24000,
    mrpPaise: 26000,
    stock: 7,
    gstPct: 5,
    origin: "Dibrugarh",
    notesForAgents: "For cups, not cutting. Pricier. Only offer if they asked for leaf.",
    substitutions: ["TEA-CUT-250"],
    perishable: false,
  },
  {
    sku: "TEA-GRN-100",
    name: "Green tea",
    aliases: ["green tea", "sabz chai", "detox tea"],
    category: "tea",
    unit: "100 g pack",
    packQty: 100,
    packUnit: "g",
    pricePaise: 28000,
    mrpPaise: 31000,
    stock: 5,
    gstPct: 5,
    origin: "Darjeeling",
    notesForAgents:
      "Darjeeling green. Health-conscious segment. Very different from CTC. Niche item, low stock.",
    substitutions: ["TEA-ASM-250"],
    perishable: false,
  },

  // ─── PAPAD ─────────────────────────────────────────────────────────────────
  {
    sku: "PAP-WAI-200",
    name: "Wai ghat papad",
    aliases: ["papad", "appalam", "wai papad", "udid papad"],
    category: "papad",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 6500,
    mrpPaise: 7000,
    stock: 25,
    gstPct: 5,
    origin: "Wai",
    notesForAgents: "Urad, not rice. Roast or fry. Hotels usually take 4–6 packs.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "PAP-RIC-200",
    name: "Rice papad",
    aliases: ["rice papad", "chawal papad", "sabudana papad"],
    category: "papad",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 7200,
    mrpPaise: 7800,
    stock: 12,
    gstPct: 5,
    origin: "Local, Patna",
    notesForAgents:
      "Thinner and more delicate than urad papad. Fry only — roasting breaks it. Tastes different.",
    substitutions: ["PAP-WAI-200"],
    perishable: false,
  },

  // ─── SUGAR & JAGGERY ────────────────────────────────────────────────────────
  {
    sku: "SGR-WHI-1",
    name: "White sugar",
    aliases: ["sugar", "chini", "cheeni", "white sugar", "table sugar"],
    category: "sugar",
    unit: "1 kg pack",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 4800,
    mrpPaise: 5200,
    stock: 50,
    gstPct: 5,
    origin: "Bihar Sugar Mills, Motihari",
    notesForAgents:
      "The most common item. Always in stock. Bihar-produced. For chai, mithai, and everything. Buyers sometimes order in bulk — up to 25 kg for events.",
    substitutions: ["SWT-JAG-1"],
    perishable: false,
  },
  {
    sku: "SWT-JAG-1",
    name: "Kolhapur jaggery",
    aliases: ["jaggery", "gul", "gud", "kolhapur gul"],
    category: "sweet",
    unit: "1 kg block",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 9800,
    mrpPaise: 11000,
    stock: 15,
    gstPct: 5,
    origin: "Kolhapur",
    notesForAgents: "Dark, wet, the proper gul. Not powder. Breaks with a knife.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "SWT-BJ-500",
    name: "Bihar jaggery (desi)",
    aliases: ["desi gud", "bihar gur", "sugarcane jaggery", "patna gur"],
    category: "sweet",
    unit: "500 g block",
    packQty: 500,
    packUnit: "g",
    pricePaise: 4200,
    mrpPaise: 4800,
    stock: 20,
    gstPct: 5,
    origin: "Champaran, Bihar",
    notesForAgents:
      "Local desi gur. Lighter in colour than Kolhapur. Less refined. Used for thekua and tilkut. Festival season demand spikes — warn buyers.",
    substitutions: ["SWT-JAG-1"],
    perishable: false,
  },

  // ─── DAIRY & GHEE ───────────────────────────────────────────────────────────
  {
    sku: "DRY-GHE-500",
    name: "Buffalo ghee",
    aliases: ["ghee", "tup", "buffalo ghee", "desi ghee"],
    category: "dairy",
    unit: "500 ml tin",
    packQty: 500,
    packUnit: "ml",
    pricePaise: 39000,
    mrpPaise: 42000,
    stock: 10,
    gstPct: 12,
    origin: "Phaltan dairy",
    notesForAgents: "Buffalo, not cow. Heavier aroma. Say so. Not cultured butter.",
    substitutions: [],
    perishable: true,
  },
  {
    sku: "DRY-GHE-1",
    name: "Cow ghee",
    aliases: ["cow ghee", "go ghee", "pure ghee", "gavya ghee"],
    category: "dairy",
    unit: "1 L tin",
    packQty: 1000,
    packUnit: "ml",
    pricePaise: 82000,
    mrpPaise: 90000,
    stock: 6,
    gstPct: 12,
    origin: "Ara dairy, Bihar",
    notesForAgents:
      "Cow ghee, not buffalo. Lighter colour and aroma. Religious households often specify this. More expensive.",
    substitutions: ["DRY-GHE-500"],
    perishable: true,
  },

  // ─── SNACKS ─────────────────────────────────────────────────────────────────
  {
    sku: "SWT-CHP-200",
    name: "Banana chips",
    aliases: ["banana chips", "kere chips", "plantain chips"],
    category: "snack",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 8500,
    mrpPaise: 9000,
    stock: 13,
    gstPct: 12,
    origin: "Kerala, packed here",
    notesForAgents: "Salted, not sweet. A snack, not a grocery staple.",
    substitutions: ["PAP-WAI-200"],
    perishable: false,
  },
  {
    sku: "SNK-MIX-200",
    name: "Patna chivda mix",
    aliases: ["chivda", "farsan", "namkeen mix", "patna mix"],
    category: "snack",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 9500,
    mrpPaise: 10500,
    stock: 18,
    gstPct: 12,
    origin: "Made in-house, Patna",
    notesForAgents:
      "Thin poha + peanuts + raisins + curry leaves. Made fresh. Best within 3 weeks. Popular for festive hampers.",
    substitutions: ["SWT-CHP-200"],
    perishable: false,
  },
  {
    sku: "SNK-TLK-200",
    name: "Tilkut (sesame sweet)",
    aliases: ["tilkut", "til laddoo", "sesame sweet", "makar sankranti sweet", "til chikki"],
    category: "snack",
    unit: "200 g box",
    packQty: 200,
    packUnit: "g",
    pricePaise: 16000,
    mrpPaise: 18000,
    stock: 8,
    gstPct: 12,
    origin: "Gaya, Bihar",
    notesForAgents:
      "Gaya tilkut — white sesame and sugar. Bihar GI product. Seasonal high demand around Makar Sankranti. Limited stock.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "SNK-SAT-500",
    name: "Sattu (roasted gram flour)",
    aliases: ["sattu", "sattu powder", "chana sattu", "roasted gram"],
    category: "snack",
    unit: "500 g pack",
    packQty: 500,
    packUnit: "g",
    pricePaise: 12000,
    mrpPaise: 13500,
    stock: 22,
    gstPct: 5,
    origin: "Jehanabad, Bihar",
    notesForAgents:
      "Bihar's protein drink — mixed with water, lemon, kala namak. Also used for litti filling. Very high demand item in summer. Not the same as besan.",
    substitutions: [],
    perishable: false,
  },

  // ─── DRY FRUITS ────────────────────────────────────────────────────────────
  {
    sku: "DRF-ALM-250",
    name: "Almonds (badam)",
    aliases: ["almond", "badam", "badaam"],
    category: "dry-fruit",
    unit: "250 g pack",
    packQty: 250,
    packUnit: "g",
    pricePaise: 42000,
    mrpPaise: 46000,
    stock: 9,
    gstPct: 5,
    origin: "California (packed in India)",
    notesForAgents:
      "Pricey, handled carefully. Often bought for puja or gifting. 250g is the standard pack. No bulk discounts without advance order.",
    substitutions: ["DRF-CSH-250"],
    perishable: false,
  },
  {
    sku: "DRF-CSH-250",
    name: "Cashews (kaju)",
    aliases: ["cashew", "kaju", "whole cashew"],
    category: "dry-fruit",
    unit: "250 g pack",
    packQty: 250,
    packUnit: "g",
    pricePaise: 52000,
    mrpPaise: 57000,
    stock: 6,
    gstPct: 5,
    origin: "Konkan",
    notesForAgents:
      "W240 grade, whole. For mithai and halwa. More expensive than almonds. Low stock — mention early.",
    substitutions: ["DRF-ALM-250"],
    perishable: false,
  },
  {
    sku: "DRF-RAS-200",
    name: "Raisins (kismis)",
    aliases: ["raisin", "kishmish", "kismis", "sultana"],
    category: "dry-fruit",
    unit: "200 g pack",
    packQty: 200,
    packUnit: "g",
    pricePaise: 16500,
    mrpPaise: 18000,
    stock: 14,
    gstPct: 5,
    origin: "Nashik",
    notesForAgents: "Seedless. For halwa, chivda, and dry fruit boxes.",
    substitutions: [],
    perishable: false,
  },

  // ─── SOAP / SOAP BAR (common in kirana stores) ──────────────────────────────
  {
    sku: "SOP-NIR-4",
    name: "Nirma washing bar",
    aliases: ["nirma", "washing soap", "kapda sabun", "washing bar"],
    category: "soap",
    unit: "4-pack (125g each)",
    packQty: 4,
    packUnit: "bar",
    pricePaise: 6400,
    mrpPaise: 6800,
    stock: 30,
    gstPct: 18,
    origin: "Ahmedabad",
    notesForAgents:
      "Laundry bar. Common household item. Hotels buy in bulk. 4-bar strip. Higher GST — 18%. Factor this into quotes.",
    substitutions: [],
    perishable: false,
  },
  {
    sku: "SOP-RIN-1",
    name: "Rin detergent powder",
    aliases: ["rin", "detergent", "washing powder", "kapda powder"],
    category: "soap",
    unit: "1 kg pouch",
    packQty: 1,
    packUnit: "kg",
    pricePaise: 11200,
    mrpPaise: 12000,
    stock: 18,
    gstPct: 18,
    origin: "HUL",
    notesForAgents:
      "Bulk laundry powder for hotels and hostels. 18% GST. Usually bought 5kg+ at a time by commercial buyers.",
    substitutions: ["SOP-NIR-4"],
    perishable: false,
  },
];

export const CATEGORY_LABEL: Record<Category, string> = {
  rice: "Rice & poha",
  atta: "Flours",
  oil: "Oils",
  spice: "Masala",
  pickle: "Pickle",
  tea: "Tea",
  papad: "Papad",
  pulse: "Dal",
  sweet: "Gul & snack",
  dairy: "Dairy",
  sugar: "Sugar",
  "dry-fruit": "Dry fruits",
  "masala-mix": "Masala mix",
  snack: "Snacks",
  soap: "Soap & detergent",
};

export function getProduct(sku: string) {
  return PRODUCTS.find((p) => p.sku === sku);
}

export function searchProducts(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return PRODUCTS;
  return PRODUCTS.filter((p) => {
    const hay = [p.name, p.sku, p.origin, p.notesForAgents, ...p.aliases, p.category]
      .join(" ")
      .toLowerCase();
    return hay.includes(q);
  });
}

export function catalogForAgents() {
  return PRODUCTS.map((p) => ({
    sku: p.sku,
    name: p.name,
    aliases: p.aliases,
    category: p.category,
    unit: p.unit,
    pack_qty: p.packQty,
    pack_unit: p.packUnit,
    price_inr: p.pricePaise / 100,
    mrp_inr: p.mrpPaise / 100,
    currency: "INR",
    stock: p.stock,
    gst_pct: p.gstPct,
    origin: p.origin,
    notes: p.notesForAgents,
    substitutions: p.substitutions,
    perishable: p.perishable,
  }));
}
